// Mock data for the Enrichment history table.
// Faithful to the values shown in the LeadMagic dashboard screenshot.

export type EnrichmentStatus = 'completed' | 'processing' | 'failed' | 'queued';

export interface EnrichmentRun {
  id: string;
  fileName: string;
  status: EnrichmentStatus;
  /** 0-100 */
  progress: number;
  rows: number;
  succeeded: number;
  /** null renders as an em-dash */
  failed: number | null;
  /** null renders as an em-dash */
  skipped: number | null;
  credits: number;
  /** human-readable, e.g. "7m 2s" */
  duration: string;
  /** e.g. "Jun 25, 2026" */
  created: string;
  /** null renders as an em-dash */
  completed: string | null;
}

export const enrichmentRuns: EnrichmentRun[] = [
  {
    id: 'run-01',
    fileName: 'Northwind Contact Enrichment List 12 - 2026 Q2 Outbound.csv',
    status: 'completed',
    progress: 100,
    rows: 429,
    succeeded: 428,
    failed: 1,
    skipped: null,
    credits: 795,
    duration: '7m 2s',
    created: 'Jun 25, 2026',
    completed: 'Jun 25, 2026',
  },
  {
    id: 'run-02',
    fileName: 'Northwind Contact Enrichment List 11 - 2026 Q2 Outbound.csv',
    status: 'completed',
    progress: 100,
    rows: 489,
    succeeded: 489,
    failed: null,
    skipped: null,
    credits: 1145,
    duration: '1m 54s',
    created: 'Jun 24, 2026',
    completed: 'Jun 24, 2026',
  },
  {
    id: 'run-03',
    fileName: 'Northwind Contact Enrichment List 10 - 2026 Q2 Outbound.csv',
    status: 'completed',
    progress: 100,
    rows: 176,
    succeeded: 176,
    failed: null,
    skipped: null,
    credits: 460,
    duration: '1m 0s',
    created: 'Jun 23, 2026',
    completed: 'Jun 23, 2026',
  },
  {
    id: 'run-04',
    fileName: 'Northwind Contact Enrichment List 9 - 2026 Q2 Outbound.csv',
    status: 'completed',
    progress: 100,
    rows: 301,
    succeeded: 301,
    failed: null,
    skipped: null,
    credits: 490,
    duration: '1m 4s',
    created: 'Jun 22, 2026',
    completed: 'Jun 22, 2026',
  },
  {
    id: 'run-05',
    fileName: 'Northwind Contact Enrichment List 8 - 2026 Q2 Outbound.csv',
    status: 'completed',
    progress: 100,
    rows: 291,
    succeeded: 135,
    failed: 156,
    skipped: null,
    credits: 500,
    duration: '1m 17s',
    created: 'Jun 22, 2026',
    completed: 'Jun 22, 2026',
  },
  {
    id: 'run-06',
    fileName: 'Northwind Contact Enrichment List 7 - 2026 Q2 Outbound.csv',
    status: 'completed',
    progress: 100,
    rows: 128,
    succeeded: 128,
    failed: null,
    skipped: null,
    credits: 260,
    duration: '10s',
    created: 'Jun 19, 2026',
    completed: 'Jun 19, 2026',
  },
  {
    id: 'run-07',
    fileName: 'Northwind Contact Enrichment List 6 - 2026 Q2 Outbound.csv',
    status: 'completed',
    progress: 100,
    rows: 148,
    succeeded: 148,
    failed: null,
    skipped: null,
    credits: 335,
    duration: '11s',
    created: 'Jun 19, 2026',
    completed: 'Jun 19, 2026',
  },
  {
    id: 'run-08',
    fileName: 'Northwind Contact Enrichment List 5 - 2026 Q2 Outbound.csv',
    status: 'completed',
    progress: 100,
    rows: 305,
    succeeded: 305,
    failed: null,
    skipped: null,
    credits: 765,
    duration: '21s',
    created: 'Jun 19, 2026',
    completed: 'Jun 19, 2026',
  },
  {
    id: 'run-09',
    fileName: 'Northwind Contact Enrichment List 4 - 2026 Q2 Outbound.csv',
    status: 'completed',
    progress: 100,
    rows: 212,
    succeeded: 209,
    failed: 3,
    skipped: null,
    credits: 430,
    duration: '34s',
    created: 'Jun 18, 2026',
    completed: 'Jun 18, 2026',
  },
  {
    id: 'run-10',
    fileName: 'Northwind Contact Enrichment List 3 - 2026 Q2 Outbound.csv',
    status: 'completed',
    progress: 100,
    rows: 540,
    succeeded: 538,
    failed: 2,
    skipped: null,
    credits: 1280,
    duration: '2m 18s',
    created: 'Jun 18, 2026',
    completed: 'Jun 18, 2026',
  },
  {
    id: 'run-11',
    fileName: 'Northwind Contact Enrichment List 2 - 2026 Q2 Outbound.csv',
    status: 'completed',
    progress: 100,
    rows: 96,
    succeeded: 96,
    failed: null,
    skipped: null,
    credits: 210,
    duration: '8s',
    created: 'Jun 17, 2026',
    completed: 'Jun 17, 2026',
  },
  {
    id: 'run-12',
    fileName: 'Northwind Contact Enrichment List 1 - 2026 Q2 Outbound.csv',
    status: 'completed',
    progress: 100,
    rows: 373,
    succeeded: 370,
    failed: 3,
    skipped: null,
    credits: 910,
    duration: '1m 41s',
    created: 'Jun 17, 2026',
    completed: 'Jun 17, 2026',
  },
  {
    id: 'run-13',
    fileName: 'Northwind ABM Target Accounts - May Refresh.csv',
    status: 'completed',
    progress: 100,
    rows: 264,
    succeeded: 261,
    failed: 3,
    skipped: null,
    credits: 612,
    duration: '47s',
    created: 'Jun 16, 2026',
    completed: 'Jun 16, 2026',
  },
  {
    id: 'run-14',
    fileName: 'Northwind Webinar Signups - Enrichment.csv',
    status: 'completed',
    progress: 100,
    rows: 418,
    succeeded: 418,
    failed: null,
    skipped: null,
    credits: 902,
    duration: '1m 33s',
    created: 'Jun 15, 2026',
    completed: 'Jun 15, 2026',
  },
  {
    id: 'run-15',
    fileName: 'Northwind Inbound Leads - Q2 Pipeline.csv',
    status: 'completed',
    progress: 100,
    rows: 152,
    succeeded: 150,
    failed: 2,
    skipped: null,
    credits: 345,
    duration: '19s',
    created: 'Jun 13, 2026',
    completed: 'Jun 13, 2026',
  },
  {
    id: 'run-16',
    fileName: 'Northwind Conference Booth Scans.csv',
    status: 'completed',
    progress: 100,
    rows: 89,
    succeeded: 89,
    failed: null,
    skipped: null,
    credits: 198,
    duration: '7s',
    created: 'Jun 12, 2026',
    completed: 'Jun 12, 2026',
  },
  {
    id: 'run-17',
    fileName: 'Northwind Partner Referrals - Enrichment.csv',
    status: 'completed',
    progress: 100,
    rows: 347,
    succeeded: 344,
    failed: 3,
    skipped: null,
    credits: 820,
    duration: '1m 12s',
    created: 'Jun 11, 2026',
    completed: 'Jun 11, 2026',
  },
];
